import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'muthuselvan' at '1/31/17 9:44 PM' with Gradle 3.2.1
 *
 * @author muthuselvan, @date 1/31/17 9:44 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        System.out.println("Testing UTF-8 compilation: C’est drôle, tout à coup je ne sais pas quoi dire.");
    }
}
